server:
  port: 8807

spring:
  application:
    name: Car Rental Services

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/client_project
    username: root
    password: Qwerty1234*

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: faizullahkhan.com.in@gmail.com
    password: mjgn aqhu awgw pgtl

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

admin:
  email: www.beingpriyanshu5555.com.in@gmail.com #write your email here for testing
#email: www.beingpriyanshu5555@gmail.com